# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Akhil Eppa"
subtitle: "See the world through my eyes!"
author: "Akhil Eppa"
header:
 title: "Photography"
 subtitle: "by Akhil Eppa"
footer:
 name: ""
 bio: ""
 github: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
